var lang=0,ajax=new XMLHttpRequest,ajaxResponseArray=[];
null!=ajax&&(ajax.overrideMimeType("text"),ajax.open("GET","api/response.php",!0),ajax.onreadystatechange=function(){4==this.readyState&&200==this.status&&(ajaxResponseArray=this.responseText.split("|"),document.getElementById("visitor_count").innerHTML="&#9733; "+ajaxResponseArray[2].toLocaleString(),-1<ajaxResponseArray[3].indexOf("de")&&(lang=1),imprintLink.innerHTML=0==lang?"Site Notice":"Impressum",document.getElementById("noop_expl").innerHTML=txtSrc[1].menuTxt[23][lang],document.getElementById("menu_reference").innerHTML=
txtSrc[1].menuTxt[24][lang],1==lang&&0==questIndex&&(itemSrc[itemSrc.length-2].src=imgPath+"menu_sign_ger_iS.png",itemSrc[itemSrc.length-3].src=imgPath+"resume_sign_ger_iS.png"),0==detectMobileDevice()?initApp():document.getElementById("mobile_screen").style.display="block")},ajax.send(null));
var imprintLink=document.getElementById("imprint_link"),mouseFollow=document.getElementById("mouseFollow"),backLink=document.getElementsByClassName("back_link"),warningContainer=document.getElementById("warning_container"),canvas0,ctx0,canvas1,ctx1,canvas2,ctx2,routeStr="",PFpath,canvas2Background=new Image,codingNightOn=!1,gameFont="9pt minecraftia",bubbleLength,action="noAction",highlighted=-1,highlightedBtn=-1,highlightedQlBtn=!1,invCursorBlink=!1,invCursorBlinkCounter=1,itemOnCursor=null,lastAddressedNpc,
convoIndex=-1,questStop=!1,HintFetchCounter=0,questMsgOn=!1,questMsgYInt=0,questMsgOut=!1,okBtnHL=!1,questMsgYIntMax=30,allItemsInPlay=[],delayByFrame=0,codingNightIndex=0,codingNightStart=!1,linesOfCode=getCookie("linesOfCode")||0,linesOfCodePerSession=0,linesOfCodeCoo=[530,180],sessionStartBtnHL=!1,sessionDenyBtnHL=!1,overlayMobile=!1,overlayBlur=!1,exTime=12096E5,clickSnd=new Audio(sndPath+"/click.mp3");clickSnd.volume=.5;var completedSnd=new Audio(sndPath+"/completed.mp3");
completedSnd.volume=.5;var vibratingSnd=new Audio(sndPath+"/mobile_vibrating.mp3");vibratingSnd.volume=.1;vibratingSnd.loop=!0;var guitarSnd=new Audio(sndPath+"/accoustic_guitar.mp3");guitarSnd.volume=0;guitarSnd.loop=!0;var guitarSndVol=.2,strAmbSnd=new Audio(sndPath+"/street_ambient.mp3");strAmbSnd.volume=1;strAmbSnd.loop=!0;var baseAmbSnd=new Audio(sndPath+"/basement_ambient.mp3");baseAmbSnd.volume=.1;baseAmbSnd.loop=!0;var doorSnd=new Audio(sndPath+"/door.mp3");doorSnd.volume=.7;
var frontDoorSnd=new Audio(sndPath+"/front_door.mp3");frontDoorSnd.volume=.5;var inputSnd=new Audio(sndPath+"/input_beep.mp3");inputSnd.volume=.7;var unlockSnd=new Audio(sndPath+"/unlock.mp3");unlockSnd.volume=.5;var metalDoorSnd=new Audio(sndPath+"/metal_door.mp3");metalDoorSnd.volume=.5;var glassSnd=new Audio(sndPath+"/throwing_glass.mp3");glassSnd.volume=.7;var lidSnd=new Audio(sndPath+"/trash_bin.mp3");lidSnd.volume=.3;var coinSnd=new Audio(sndPath+"/coin_drop.mp3");coinSnd.volume=1;
var glitchSnd=new Audio(sndPath+"/glitch1.mp3");glitchSnd.volume=1;
var fastModeOn=!1,soundOn=!0,clickSndOn=!0,guitarSndFade="none",helpingOverlayOn=!1,highlightedEngBtn=!1,highlightedGerBtn=!1,highlightedFastModeBtn=!1,highlightedSoundOffBtn=!1,highlightedHelpBtn=!1,highlightedReachBtn=!1,highlightedTransBtn=!1,highlightedResetBtn=!1,highlightedExplBtn=!1,highlightedDropzone=null,remOldSceneIndex,allDroppedItems=[],accessKey=[4,2,5,3,1,9,7,6],uniTrigger=!1,lilStoryHelper1=!1,lilStoryHelper2=!1,lilStoryHelper3=!1,lilStoryHelper4=!1,hoverTriggerExitZone=-1,hoverTriggerWalkingZone=
!1,reachabilityOn=!0,transcriptOn=!0,version=detectIE(),framesPerSecond=0!=version?60:40,framesPerSecondBase=1E3,wayPointCount=0,transfer=0,walkingSpeed=4,frameCounter=0,frameCounterTarget=-1,clicksPerQuest=0,Scene,Inv,Mobile,questIndex,Menu,Expl,Bennet,mobileBtn=document.getElementById("mobileBtn");mobileBtn.addEventListener("click",function(a){initApp()});
function initApp(){document.getElementById("mobile_screen").style.display="none";document.getElementById("loading_bar_container").style.display="block";document.getElementById("loading_bar_container").style.width="980px";document.getElementById("loading_counter").style.display="block";document.getElementById("loading_counter").style.width="984px";try{for(var a=new PxLoader,c=0;18>c;c++){var b=new PxLoaderImage("img/scenes/codingNight/sc00_codingNight_"+c+".png");a.add(b)}for(c=0;c<itemSrc.length;c++)b=
new PxLoaderImage(itemSrc[c].src),a.add(b);for(c=0;c<charSrc.length;c++)b=new PxLoaderImage(charSrc[c].src),a.add(b);for(c=0;c<sceneSrc.length;c++)b=new PxLoaderImage(sceneSrc[c].bgImgSrc),a.add(b),"undefined"!=typeof sceneSrc[c].fgImgSrc&&(b=new PxLoaderImage(sceneSrc[c].fgImgSrc),a.add(b));a.add(new PxLoaderImage(imgPath+"crosshair.cur"));a.add(new PxLoaderImage(imgPath+"crosshair_dark.cur"));a.add(new PxLoaderImage(imgPath+"walking.cur"));a.add(new PxLoaderImage(imgPath+"look.cur"));a.add(new PxLoaderImage(imgPath+
"grab.cur"));a.add(new PxLoaderImage(imgPath+"grabbing.cur"));a.add(new PxLoaderImage(imgPath+"wrench.cur"));a.add(new PxLoaderImage(imgPath+"pointer.cur"));a.add(new PxLoaderImage(imgPath+"talk.cur"));a.add(new PxLoaderImage(imgPath+"talking.cur"));a.add(new PxLoaderImage(imgPath+"exit_down.cur"));a.add(new PxLoaderImage(imgPath+"exit_left.cur"));a.add(new PxLoaderImage(imgPath+"exit_right.cur"));a.add(new PxLoaderImage(imgPath+"exit_up.cur"));a.add(new PxLoaderImage("img/scenes/sc01_hallway_fg.png"));
a.add(new PxLoaderImage("img/scenes/codingNight/sc00_codingNight_start.png"));a.add(new PxLoaderImage("img/scenes/sc00_apartment_fg_emptyWardrobe.png"));a.add(new PxLoaderImage(imgPath+"glitch_00.png"));a.add(new PxLoaderImage(imgPath+"glitch_01.png"));a.add(new PxLoaderImage(imgPath+"mobile_overlay.png"));a.add(new PxLoaderImage(imgPath+"explanation_overlay.png"));a.add(new PxLoaderImage(imgPath+"bg_00.png"));a.add(new PxLoaderImage(imgPath+"bennet_walking_all_parka.png"));a.add(new PxLoaderImage(imgPath+
"bennet_idling_front_parka.png"));a.addProgressListener(function(a){var b=Math.round(100*a.completedCount/a.totalCount);document.getElementById("loading_counter").innerHTML="Loading . . . "+a.completedCount+" / "+a.totalCount;document.getElementById("loading_bar").style.left=b-100+"%"});a.addCompletionListener(function(){document.getElementById("loading_screen").classList.add("loaded");document.getElementById("container").style.display="block";15<version&&(document.getElementById("warning_container").style.display=
"block",document.getElementById("warning").innerHTML=txtSrc[1].menuTxt[21][lang],document.getElementById("dismiss_warning").innerHTML=txtSrc[1].menuTxt[22][lang]);0!=questIndex&&Bennet.setSpeech(txtSrc[4].bennetStoryTxt[questIndex][lang])});a.start()}catch(e){console.warn(e),document.getElementById("loading_counter").style.color="#FF3F3F",document.getElementById("loading_counter").innerHTML="Error while loading resources &nbsp; - &nbsp; try reload"}initCanvas();initGame();canvas1.addEventListener("mouseup",
getClickPosition,!1);canvas2.addEventListener("mouseup",getClickPosition,!1);canvas1.addEventListener("mousemove",getHoverPosition,!1);canvas2.addEventListener("mousemove",getHoverPosition,!1);canvas1.addEventListener("mouseout",leaveCanvas,!1);canvas2.addEventListener("mouseout",leaveCanvas,!1);canvas1.addEventListener("mouseover",enterCanvas,!1);canvas2.addEventListener("mouseover",enterCanvas,!1);canvas1.addEventListener("contextmenu",hideMouseFollow,!1);mouseFollow.addEventListener("mouseover",
hideMouseFollow,!1);imprintLink.addEventListener("mouseover",imprintLinkHover,!1);imprintLink.addEventListener("mouseout",imprintLinkMouseOut,!1);imprintLink.addEventListener("mouseup",imprintLinkClick,!1);backLink[0].addEventListener("mouseover",backLinkHover,!1);backLink[0].addEventListener("mouseout",backLinkMouseOut,!1);backLink[0].addEventListener("mouseup",backLinkClick,!1);backLink[1].addEventListener("mouseover",backLinkHover,!1);backLink[1].addEventListener("mouseout",backLinkMouseOut,!1);
backLink[1].addEventListener("mouseup",backLinkClick,!1);warningContainer.addEventListener("mouseup",hideWarning,!1);imprintLink.innerHTML=0==lang?"Site Notice":"Impressum";document.onkeydown=function(a){a=a||window.event;if(27==a.keyCode)"block"==document.getElementById("imprint_screen_eng").style.display||"block"==document.getElementById("imprint_screen_ger").style.display?(document.getElementById("imprint_screen_eng").style.display="none",document.getElementById("imprint_screen_ger").style.display=
"none"):"block"==canvas2.style.display&&1==codingNightOn?(canvas2.style.display="none",codingNightStart=codingNightOn=!1,Inv.writeLog(txtSrc[2].actions[13][lang]),Inv.writeLog(txtSrc[2].actions[14][lang].replace("*var*",linesOfCodePerSession)),linesOfCodePerSession=0):0==Scene.index&&1==Expl.active?(Expl.active=!1,Scene.transition=[2,9],switchScene(Scene.index),canvas2.style.display="block",Menu.active=!0,1==soundOn&&doorSnd.play(),document.getElementById("menu_reference").style.display="none"):9!=
Scene.index&&"none"==canvas2.style.display&&"inConvo"!=action?(Scene.transition=[2,9],switchScene(Scene.index),canvas2.style.display="block",Menu.active=!0,guitarSndFade="fadeOut",1==soundOn&&doorSnd.play(),document.getElementById("menu_reference").style.display="none"):"block"==document.getElementById("warning_container").style.display&&(document.getElementById("warning_container").style.display="none");else if(6==Scene.index){var b=document.getElementsByClassName("digits");for(c=0;c<b.length;c++)b[c].onkeyup=
function(a){a=a.keyCode;"!"==this.value||'"'==this.value||"\u00a7"==this.value||"$"==this.value||"%"==this.value||"&"==this.value||"/"==this.value||"("==this.value||")"==this.value||"="==this.value?(Bennet.setSpeech(txtSrc[0].react[26][lang]),this.value="",this.value.trim()):(48>a||57<a)&&(96>a||105<a)&&8!=a&&9!=a&&46!=a&&(37>a||40<a)?(Bennet.setSpeech(txtSrc[0].react[26][lang]),this.value="",this.value.trim()):8!=a&&9!=a&&46!=a&&(37>a||40<a)&&null!=this.nextElementSibling&&(1==soundOn&&inputSnd.play(),
this.nextElementSibling.focus(),this.nextElementSibling.value="");8==a&&46!=a&&null!=this.previousElementSibling&&this.previousElementSibling.focus();8==c&&validateInputPanel(b)}}};refreshLangInInv();mainLoop()}function hideWarning(a){"block"==document.getElementById("warning_container").style.display&&(document.getElementById("warning_container").style.display="none")}
function leaveCanvas(a){highlightedBtn=highlighted=-1;highlightedResetBtn=highlightedHelpBtn=highlightedSoundOffBtn=highlightedGerBtn=highlightedEngBtn=highlightedQlBtn=!1;"default"!==document.body.style.cursor&&"noAction"==action&&0==Mobile.active&&(document.body.style.cursor="default");mouseFollow.style.display="none";hoverTriggerExitZone=-1;hoverTriggerWalkingZone=!1}
function enterCanvas(a){"default"==document.body.style.cursor&&"noAction"==action&&(document.body.style.cursor="url("+imgPath+"crosshair.cur), crosshair")}function hideMouseFollow(a){mouseFollow.style.display="none";a.preventDefault()}function imprintLinkHover(a){document.body.style.cursor="pointer";document.getElementById("imprint_link").style.color="#aaa"}function imprintLinkMouseOut(a){document.body.style.cursor="default";document.getElementById("imprint_link").style.color="#555"}
function imprintLinkClick(a){document.body.style.cursor="default";document.getElementById("imprint_link").style.color="#555";0==lang?document.getElementById("imprint_screen_eng").style.display="block":document.getElementById("imprint_screen_ger").style.display="block"}function backLinkHover(a){document.body.style.cursor="pointer";document.getElementById("back_link_ger").style.color="#ccc";document.getElementById("back_link_eng").style.color="#ccc"}
function backLinkMouseOut(a){document.body.style.cursor="default";document.getElementById("back_link_ger").style.color="#777";document.getElementById("back_link_eng").style.color="#777"}
function backLinkClick(a){document.body.style.cursor="default";document.getElementById("back_link_ger").style.color="#777";document.getElementById("back_link_eng").style.color="#777";document.getElementById("imprint_screen_ger").style.display="none";document.getElementById("imprint_screen_eng").style.display="none"}
function getHoverPosition(a){var c=canvas1.getBoundingClientRect(),b=[];b[0]=Math.round(a.clientX-c.left);b[1]=Math.round(a.clientY-c.top);frameCounter>.1*framesPerSecond&&(1==codingNightOn?codingNightHover(b):1==Mobile.active?mobileHover(b):1==questMsgOn&&questMsgYInt>questMsgYIntMax-5?questMsgHover(b):1==Expl.active?explHover(b):doSomethingOnHover(b));1==Menu.active&&menuHover(b);"default"==document.body.style.cursor&&(document.body.style.cursor="url("+imgPath+"crosshair.cur), crosshair")}
function getClickPosition(a){a=a||window.event;if(0===a.button){var c=canvas1.getBoundingClientRect(),b=[];b[0]=Math.round(a.clientX-c.left);b[1]=Math.round(a.clientY-c.top);1==Menu.active&&"noAction"==action&&menuClick(b);1==codingNightOn?codingNightClick(b):1==Mobile.active?mobileClick(b):1==questMsgOn&&questMsgYInt>questMsgYIntMax-5?questMsgClick(b):1==Expl.active?explClick(b):(doSomethingOnClick(b),setActionOnClick(b),setCursorOnClick());1==clickSndOn&&1==soundOn&&clickSnd.play();clickSndOn=!0}}
function getGridPos(a,c){if(a[0]<=Scene.walkable[1][0]&&a[1]<=Scene.walkable[1][1]&&a[0]>=Scene.walkable[0][0]&&a[1]>=Scene.walkable[0][1]){for(var b=[],e=[],d=0;d<Scene.meshwork[0].length;d++)a[0]<=Scene.meshwork[0][d][0]+Scene.Grid.meshSize/2&&(b[0]=Scene.meshwork[0][d][0],e[0]=d,d=Scene.meshwork[0].length);for(d=0;d<=Scene.meshwork.length;d++)a[1]<Scene.meshwork[d][0][1]+Scene.Grid.meshSize/2&&(b[1]=Scene.meshwork[d][0][1],e[1]=d,d=Scene.meshwork.length)}else e=!1;return"pixel"==c?b:"matrix"==
c?e:!1}
function mainLoop(){setTimeout(function(){ctx1.clearRect(0,0,canvas1.width,canvas1.height);Inv.render(ctx1);null!=highlightedDropzone&&null!==itemOnCursor&&dropZoneRenderHighlight(ctx1);if("undefined"!==typeof Scene.itemsInScene)for(var a=0;a<Scene.itemsInScene.length;a++)Scene.itemsInScene[a].render(ctx1);if("undefined"!==typeof Scene.npcInScene)for(a=0;a<Scene.npcInScene.length;a++)Scene.npcInScene[a].render(ctx1);Bennet.render(ctx1);if("undefined"!==typeof Scene.npcInScene)for(a=0;a<Scene.npcInScene.length;a++)1==Scene.npcInScene[a].chatOn&&
Scene.npcInScene[a].renderChat(ctx1);Scene.foreground&&ctx1.drawImage(Scene.foreground,0,0);1==Bennet.chatOn&&Bennet.renderChat(ctx1);0<Inv.highlightHintBtnIndex&&renderHintHighlighter(ctx1);null!==itemOnCursor&&itemOnCursor.render(ctx1);1==Mobile.active&&Mobile.render(ctx2);1==codingNightOn&&codingNightRender(ctx2);1==questMsgOn&&questMsgRender(ctx2);frameCounterTarget==frameCounter&&glitchTrigger();"none"!=guitarSndFade&&1==soundOn&&fadeSnd(guitarSnd,guitarSndVol);1==Menu.active&&(ctx2.clearRect(0,
0,canvas2.width,canvas2.height),Menu.render(ctx2));1==Expl.active&&(ctx2.clearRect(0,0,canvas2.width,canvas2.height),Expl.render(ctx2));requestAnimationFrame(mainLoop);frameCounter++},framesPerSecondBase/framesPerSecond)};